name: Trigger workflow

on: 
  push: 
     branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
  
  trigger:
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 4
    needs:
        - build
    steps:
        - uses: actions/checkout@v1

        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' 
            
        - name: Trigger next workflow
          if: success()
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.REPO_GHA_PAT }}
            repository: ${{ github.repository }}
            event-type: trigger-workflow-2
            client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
